// Table data for Estate Billing & Payments
export const estateBillingData = [
  {
    _id: 'bill_0',
    billName: 'Annual Estate Dues',
    amount: '₦10,000',
    frequency: 'Quarterly',
    startDate: '22 Aug, 2025',
    status: 'Active',
    residenceType: 'Detached House/Bungalow',
  },
  {
    _id: 'bill_1',
    billName: 'Monthly Security Fee',
    amount: '₦5,000',
    frequency: 'Monthly',
    startDate: '18 Aug, 2025',
    status: 'Inactive',
    residenceType: 'Shop/Store',
  },
  {
    _id: 'bill_2',
    billName: 'General Service Charge',
    amount: '₦6,000',
    frequency: 'Monthly',
    startDate: '18 Aug, 2025',
    status: 'Inactive',
    residenceType: 'Flat/Apartment',
  },
  {
    _id: 'bill_3',
    billName: 'Weekly Cleaning',
    amount: '₦2,500',
    frequency: 'Weekly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Detached House/Bungalow',
  },
  {
    _id: 'bill_4',
    billName: 'Biweekly Estate Dues',
    amount: '₦10,000',
    frequency: 'Biweekly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Shop/Store',
  },
  {
    _id: 'bill_5',
    billName: 'Monthly Security Fee',
    amount: '₦5,000',
    frequency: 'Monthly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Flat/Apartment',
  },
  {
    _id: 'bill_6',
    billName: 'Monthly Service Charge',
    amount: '₦6,500',
    frequency: 'Monthly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Detached House/Bungalow',
  },
  {
    _id: 'bill_7',
    billName: 'Monthly Security Fee',
    amount: '₦5,000',
    frequency: 'Monthly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Shop/Store',
  },
  {
    _id: 'bill_8',
    billName: 'Biweekly Estate Dues',
    amount: '₦10,000',
    frequency: 'Biweekly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Flat/Apartment',
  },
  {
    _id: 'bill_9',
    billName: 'Weekly Cleaning',
    amount: '₦2,500',
    frequency: 'Weekly',
    startDate: '21 Aug, 2025',
    status: 'Active',
    residenceType: 'Detached House/Bungalow',
  },
  // Repeat similar objects to reach 30 entries
  ...Array.from({ length: 20 }, (_, i) => ({
    _id: `bill_${10 + i}`,
    billName: [
      'Annual Estate Dues',
      'Monthly Security Fee',
      'General Service Charge',
      'Weekly Cleaning',
      'Biweekly Estate Dues',
      'Monthly Service Charge',
    ][i % 6],
    amount: `₦${(i % 3 === 0 ? 10000 : i % 3 === 1 ? 5000 : 6000) + i * 100}`,
    frequency: ['Monthly', 'Quarterly', 'Weekly', 'Biweekly'][i % 4],
    startDate: `${21 + (i % 10)} Aug, 2025`,
    status: i % 4 === 0 ? 'Inactive' : 'Active',
    residenceType: ['Detached House/Bungalow', 'Shop/Store', 'Flat/Apartment'][i % 3],
  })),
];
